<h2>What is a cupcake?</h2>
<p>A cupcake (also British English: fairy cake; Hiberno-English: bun; Australian English: fairy cake or patty cake) 
is a small cake designed to serve one person, which may be baked in a small thin paper or aluminum cup. As with 
larger cakes, icing and other cake decorations such as fruit and candy may be applied.</p>


<h2>Cupcake History</h2>
<p>The earliest extant description of what is now often called a cupcake was in 1796, when a recipe for "a light cake to bake in small cups" was written in American Cookery by Amelia Simmons. The earliest extant documentation of the term cupcake itself was in "Seventy-five Receipts for Pastry, Cakes, and Sweetmeats" in 1828 in Eliza Leslie's Receipts cookbook.</p>
<p>In the early 19th century, there were two different uses for the term cup cake or cupcake. In previous centuries, before muffin tins were widely available, the cakes were often baked in individual pottery cups, ramekins, or molds and took their name from the cups they were baked in. This is the use of the name that has remained, and the name of "cupcake" is now given to any small, round cake that is about the size of a teacup. While English fairy cakes vary in size more than American cupcake, they are traditionally smaller and are rarely topped with elaborate icing.</p>
<p>The other kind of "cup cake" referred to a cake whose ingredients were measured by volume, using a standard-sized cup, instead of being weighed. Recipes whose ingredients were measured using a standard-sized cup could also be baked in cups; however, they were more commonly baked in tins as layers or loaves. In later years, when the use of volume measurements was firmly established in home kitchens, these recipes became known as 1234 cakes or quarter cakes, so called because they are made up of four ingredients: one cup of butter, two cups of sugar, three cups of flour, and four eggs. They are plain yellow cakes, somewhat less rich and less expensive than pound cake, due to using about half as much butter and eggs compared to pound cake.</p>
<p>The names of these two major classes of cakes were intended to signal the method to the baker; "cup cake" uses a volume measurement, and "pound cake" uses a weight measurement.</p>

<h2>Making Cupcakes</h2>
<p>A standard cupcake uses the same basic ingredients as standard-sized cakes: butter, sugar, eggs, and flour. Nearly any recipe that is suitable for a layer cake can be used to bake cupcakes. The cake batter used for cupcakes may be flavored or have other ingredients stirred in, such as raisins, berries, nuts, or chocolate chips.</p>
<p>Because their small size is more efficient for heat conduction, cupcakes bake much faster than a normal layered cake. During baking, the volume of the batter initially increases due to the production of carbon dioxide, then decreases upon cooling due to the release of leavening gases.</p>
<p>Cupcakes may be topped with frosting or other cake decorations. They may be filled with frosting, fruit, or pastry cream. For bakers making a small number of filled cupcakes, this is usually accomplished by using a spoon or knife to scoop a small hole in the top of the cupcake. Another method is to just insert the pastry bag in the middle of the cupcake. In commercial bakeries, the filling may be injected using a syringe. Elaborately decorated cupcakes may be made for special occasions.</p>

<h2>Cupcake Variants</h2>
<p>A cake in a mug is a variant that gained popularity on many internet cooking forums and mailing lists. The technique uses a mug as its cooking vessel and can be done in a microwave oven. The recipe often takes fewer than five minutes to prepare. The cake rises by mixing vegetable oil (usually olive oil or sunflower oil) into a mixture of flour and other ingredients - as the oil in the mixture heats up, it creates air pockets in the mixture which allows the cake to quickly rise. This variant has become popularised in recent years by the presence of numerous videos on social media websites, each claiming to detail the fastest method to create the finished product.</p>
<p>A cake in a jar is another way of making cupcakes. The baker uses a glass jar instead of muffin tins or cupcake liners.
A butterfly cake is a variant of cupcake, also called fairy cake for its fairy-like "wings". They can be made from any flavor of cake. The top of the fairy cake is cut off or carved out with a spoon, and cut in half. Then, butter cream, whipped cream or other sweet filling (e.g. jam) is spread into the hole. Finally, the two cut halves are stuck into the butter cream to resemble butterfly wings. The wings of the cake are often decorated using icing to form various patterns.</p>
<p>A cake ball is an individual portion of cake, round like a chocolate truffle, that is coated in chocolate. These are typically formed from crumbled cake mixed with frosting, rather than being baked as a sphere. Cake balls are typically sold on sticks as cake pops</p>
<p>A gourmet cupcake is a somewhat recent variant of cupcake. Gourmet cupcakes are large and filled cupcakes, based around a variety of flavor themes, such as Tiramisu or Cappuccino. In recent years there has been an upcropping of stores that sell only gourmet cupcakes in metropolitan areas.
As an alternative to a plate of individual cakes, some bakers place standard cupcakes into a pattern and frost them to create a large design, such as a basket of flowers or a turtle.</p>